include ../Make.defines

prodcons2:		prodcons2.o
		${CC} ${CFLAGS} -o $@ $^ ${LIBS}
prodcons3:		prodcons3.o
		${CC} ${CFLAGS} -o $@ $^ ${LIBS}
prodcons6:		prodcons6.o
		${CC} ${CFLAGS} -o $@ $^ ${LIBS}
clean:
		rm -f ${CLEANFILES}